import tooth11 from "../images/Ortho-teeth/1stquadrant/11.png";
import tooth12 from "../images/Ortho-teeth/1stquadrant/12.png";
import tooth13 from "../images/Ortho-teeth/1stquadrant/13.png";
import tooth14 from "../images/Ortho-teeth/1stquadrant/14.png";
import tooth15 from "../images/Ortho-teeth/1stquadrant/15.png";
import tooth16 from "../images/Ortho-teeth/1stquadrant/16.png";
import tooth17 from "../images/Ortho-teeth/1stquadrant/17.png";
import tooth18 from "../images/Ortho-teeth/1stquadrant/18.png";
import tooth21 from "../images/Ortho-teeth/2ndquadrant/21.png";
import tooth22 from "../images/Ortho-teeth/2ndquadrant/22.png";
import tooth23 from "../images/Ortho-teeth/2ndquadrant/24.png";
import tooth24 from "../images/Ortho-teeth/2ndquadrant/24.png";
import tooth25 from "../images/Ortho-teeth/2ndquadrant/25.png";
import tooth26 from "../images/Ortho-teeth/2ndquadrant/26.png";
import tooth27 from "../images/Ortho-teeth/2ndquadrant/27.png";
import tooth28 from "../images/Ortho-teeth/2ndquadrant/28.png";

import tooth41 from "../images/Ortho-teeth/3rdquadrant/31.png";
import tooth42 from "../images/Ortho-teeth/3rdquadrant/32.png";
import tooth43 from "../images/Ortho-teeth/3rdquadrant/33.png";
import tooth44 from "../images/Ortho-teeth/3rdquadrant/34.png";
import tooth45 from "../images/Ortho-teeth/3rdquadrant/35.png";
import tooth46 from "../images/Ortho-teeth/3rdquadrant/36.png";
import tooth47 from "../images/Ortho-teeth/3rdquadrant/37.png";
import tooth48 from "../images/Ortho-teeth/3rdquadrant/38.png";
import tooth31 from "../images/Ortho-teeth/4thquadrant/41.png";
import tooth32 from "../images/Ortho-teeth/4thquadrant/42.png";
import tooth33 from "../images/Ortho-teeth/4thquadrant/43.png";
import tooth34 from "../images/Ortho-teeth/4thquadrant/44.png";
import tooth35 from "../images/Ortho-teeth/4thquadrant/45.png";
import tooth36 from "../images/Ortho-teeth/4thquadrant/46.png";
import tooth37 from "../images/Ortho-teeth/4thquadrant/47.png";
import tooth38 from "../images/Ortho-teeth/4thquadrant/48.png";
import toothIcon from "../images/Ortho-teeth/buttonIcon/toothIcon.png";

// button icons for wire and brackets
import wireButtonIcon from "../images/Icons/wireIcon.png";
import bracket1Icon from "../images/Icons/bracketType1Icon.png";
import bracket2Icon from "../images/Icons/bracketType2Icon.png";
import bracket3Icon from "../images/Icons/bracketType3Icon.png";

// chain
import chain1Icon from "../images/Icons/chainType1Icon.png";
import chain2Icon from "../images/Icons/chainType2Icon.png";
import chain3Icon from "../images/Icons/chainType3Icon.png";

//functions icon
import function1Icon from "../images/Ortho-teeth/buttonIcon/function1.png";
import function2Icon from "../images/Ortho-teeth/buttonIcon/function2.png";
import function3Icon from "../images/Ortho-teeth/buttonIcon/function3.png";
import function4Icon from "../images/Ortho-teeth/buttonIcon/function4.png";

// importing implant tooth images
import implant18 from "../images/Ortho-teeth/implant/implant18.png";
import implant17 from "../images/Ortho-teeth/implant/implant17.png";
import implant16 from "../images/Ortho-teeth/implant/implant16.png";
import implant15 from "../images/Ortho-teeth/implant/implant15.png";
import implant14 from "../images/Ortho-teeth/implant/implant14.png";
import implant13 from "../images/Ortho-teeth/implant/implant13.png";
import implant12 from "../images/Ortho-teeth/implant/implant12.png";
import implant11 from "../images/Ortho-teeth/implant/implant11.png";
import implant21 from "../images/Ortho-teeth/implant/implant21.png";
import implant22 from "../images/Ortho-teeth/implant/implant22.png";
import implant23 from "../images/Ortho-teeth/implant/implant23.png";
import implant24 from "../images/Ortho-teeth/implant/implant24.png";
import implant25 from "../images/Ortho-teeth/implant/implant25.png";
import implant26 from "../images/Ortho-teeth/implant/implant26.png";
import implant27 from "../images/Ortho-teeth/implant/implant27.png";
import implant28 from "../images/Ortho-teeth/implant/implant28.png";
import implant38 from "../images/Ortho-teeth/implant/implant38.png";
import implant37 from "../images/Ortho-teeth/implant/implant37.png";
import implant36 from "../images/Ortho-teeth/implant/implant36.png";
import implant35 from "../images/Ortho-teeth/implant/implant35.png";
import implant34 from "../images/Ortho-teeth/implant/implant34.png";
import implant33 from "../images/Ortho-teeth/implant/implant33.png";
import implant32 from "../images/Ortho-teeth/implant/implant32.png";
import implant31 from "../images/Ortho-teeth/implant/implant31.png";
import implant41 from "../images/Ortho-teeth/implant/implant41.png";
import implant42 from "../images/Ortho-teeth/implant/implant42.png";
import implant43 from "../images/Ortho-teeth/implant/implant43.png";
import implant44 from "../images/Ortho-teeth/implant/implant44.png";
import implant45 from "../images/Ortho-teeth/implant/implant45.png";
import implant46 from "../images/Ortho-teeth/implant/implant46.png";
import implant47 from "../images/Ortho-teeth/implant/implant47.png";
import implant48 from "../images/Ortho-teeth/implant/implant48.png";

// importing cavity images
import cavity18 from "../images/Ortho-teeth/cavity/cavity18.png";
import cavity17 from "../images/Ortho-teeth/cavity/cavity17.png";
import cavity16 from "../images/Ortho-teeth/cavity/cavity16.png";
import cavity15 from "../images/Ortho-teeth/cavity/cavity15.png";
import cavity14 from "../images/Ortho-teeth/cavity/cavity14.png";
import cavity13 from "../images/Ortho-teeth/cavity/cavity13.png";
import cavity12 from "../images/Ortho-teeth/cavity/cavity12.png";
import cavity11 from "../images/Ortho-teeth/cavity/cavity11.png";
import cavity21 from "../images/Ortho-teeth/cavity/cavity21.png";
import cavity22 from "../images/Ortho-teeth/cavity/cavity22.png";
import cavity23 from "../images/Ortho-teeth/cavity/cavity23.png";
import cavity24 from "../images/Ortho-teeth/cavity/cavity24.png";
import cavity25 from "../images/Ortho-teeth/cavity/cavity25.png";
import cavity26 from "../images/Ortho-teeth/cavity/cavity26.png";
import cavity27 from "../images/Ortho-teeth/cavity/cavity27.png";
import cavity28 from "../images/Ortho-teeth/cavity/cavity28.png";
import cavity38 from "../images/Ortho-teeth/cavity/cavity38.png";
import cavity37 from "../images/Ortho-teeth/cavity/cavity37.png";
import cavity36 from "../images/Ortho-teeth/cavity/cavity36.png";
import cavity35 from "../images/Ortho-teeth/cavity/cavity35.png";
import cavity34 from "../images/Ortho-teeth/cavity/cavity34.png";
import cavity33 from "../images/Ortho-teeth/cavity/cavity33.png";
import cavity32 from "../images/Ortho-teeth/cavity/cavity32.png";
import cavity31 from "../images/Ortho-teeth/cavity/cavity31.png";
import cavity41 from "../images/Ortho-teeth/cavity/cavity41.png";
import cavity42 from "../images/Ortho-teeth/cavity/cavity42.png";
import cavity43 from "../images/Ortho-teeth/cavity/cavity43.png";
import cavity44 from "../images/Ortho-teeth/cavity/cavity44.png";
import cavity45 from "../images/Ortho-teeth/cavity/cavity45.png";
import cavity46 from "../images/Ortho-teeth/cavity/cavity46.png";
import cavity47 from "../images/Ortho-teeth/cavity/cavity47.png";
import cavity48 from "../images/Ortho-teeth/cavity/cavity48.png";

// button icon import here
import cavityIcon from "../images/Icons/cavityIcon.png";
import chainIcon from "../images/Icons/chainIcon.png";
import implantIcon from "../images/Icons/implantIcon.png";
import rubberBandIcon from "../images/Icons/rubberBandIcon.png";
import wireIcon from "../images/Icons/wireIcon.jpg"; //wire icon
import coiledSpring from "../images/Icons/springIcon.png"; // spring coil
import bracketIcon from "../images/Icons/bracketIcon.jpeg"; // bracket Icon

export const logs = [
 {log_id: 1	,  id:18,	name:"tooth18", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 2	,  id:17,	name:"tooth17", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 3	,  id:16,	name:"tooth16", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 4	,  id:15,	name:"tooth15", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 5	,  id:14,	name:"tooth14", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 6	,  id:13,	name:"tooth13", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 7	,  id:12,	name:"tooth12", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 8	,  id:11,	name:"tooth11", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 9	,  id:21,	name:"tooth21", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 10,	 id:22	,name:"tooth22", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 11,	 id:23	,name:"tooth23", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 12,	 id:24	,name:"tooth24", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 13,	 id:25	,name:"tooth25", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 14,	 id:26	,name:"tooth26", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 15,	 id:27	,name:"tooth27", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 16,	 id:28	,name:"tooth28", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 17,	 id:38	,name:"tooth38", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 18,	 id:37	,name:"tooth37", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 19,	 id:36	,name:"tooth36", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 20,	 id:35	,name:"tooth35", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 21,	 id:34	,name:"tooth34", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 22,	 id:33	,name:"tooth33", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 23,	 id:32	,name:"tooth32", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 24,	 id:31	,name:"tooth31", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 25,	 id:41	,name:"tooth41", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 26,	 id:42	,name:"tooth42", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 27,	 id:43	,name:"tooth43", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 28,	 id:44	,name:"tooth44", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 29,	 id:45	,name:"tooth45", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 30,	 id:46	,name:"tooth46", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 31,	 id:47	,name:"tooth47", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
{log_id: 32,	 id:48	,name:"tooth48", date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:"",
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,},
  {
    id: 17,
    name: "tooth17",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 16,
    name: "tooth16",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 15,
    name: "tooth15",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 14,
    name: "tooth14",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 13,
    name: "tooth13",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 12,
    name: "tooth12",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 11,
    name: "tooth11",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 21,
    name: "tooth21",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 22,
    name: "tooth22",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 23,
    name: "tooth23",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 24,
    name: "tooth24",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 25,
    name: "tooth25",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 26,
    name: "tooth26",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 27,
    name: "tooth27",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 28,
    name: "tooth28",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 38,
    name: "tooth38",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 37,
    name: "tooth37",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 36,
    name: "tooth36",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 35,
    name: "tooth35",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 34,
    name: "tooth34",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 33,
    name: "tooth33",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 32,
    name: "tooth32",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 31,
    name: "tooth31",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 41,
    name: "tooth41",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 42,
    name: "tooth42",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 43,
    name: "tooth43",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 44,
    name: "tooth44",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 45,
    name: "tooth45",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 46,
    name: "tooth46",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,

  },
  {
    id: 47,
    name: "tooth47",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
  {
    id: 48,
    name: "tooth48",
    date:null,
    value: 0,
    log:null,
    bracket: false,
    bracketStartsHere: false,
    bracketRangeComment:null,
    bracketRangeArray: [],
    bracketIconValue: 0,
    bracketRangeEndToothName:null,
    wire: false,
    wireStartsHere: false,
    wireRangeComment:null,
    wireRangeEndToothName:null,
    wireRangeArray: [],
    chain: false,
    chainStartsHere: false,
    chainRangeComment:null,
    chainRangeEndToothName:null,
    chainRangeArray: [],
    chainIconValue: 0,
    coiledSpring: false,
    canvasImage:null,
    rubberBand: false,
    rubberBandComment:null,
    coiledSpringComment:null,
  },
];

type teethImageType={
  [k:string]:string[]
}

export const teethImage:teethImageType = {
  bracket: [bracket1Icon, bracket2Icon, bracket3Icon],
  icons: [
    cavityIcon,
    implantIcon,
    bracketIcon,
    chainIcon,
    wireIcon,
    rubberBandIcon,
    coiledSpring,
  ],
  chain: [chain1Icon, chain2Icon, chain3Icon],
  tooth18: [tooth18, cavity18, implant18],
  tooth17: [tooth17, cavity17, implant17],
  tooth16: [tooth16, cavity16, implant16],
  tooth15: [tooth15, cavity15, implant15],
  tooth14: [tooth14, cavity14, implant14],
  tooth13: [tooth13, cavity13, implant13],
  tooth12: [tooth12, cavity12, implant12],
  tooth11: [tooth11, cavity11, implant11],
  tooth21: [tooth21, cavity21, implant21],
  tooth22: [tooth22, cavity22, implant22],
  tooth23: [tooth23, cavity23, implant23],
  tooth24: [tooth24, cavity24, implant24],
  tooth25: [tooth25, cavity25, implant25],
  tooth26: [tooth26, cavity26, implant26],
  tooth27: [tooth27, cavity27, implant27],
  tooth28: [tooth28, cavity28, implant28],
  tooth38: [tooth38, cavity38, implant38],
  tooth37: [tooth37, cavity37, implant37],
  tooth36: [tooth36, cavity36, implant36],
  tooth35: [tooth35, cavity35, implant35],
  tooth34: [tooth34, cavity34, implant34],
  tooth33: [tooth33, cavity33, implant33],
  tooth32: [tooth32, cavity32, implant32],
  tooth31: [tooth31, cavity31, implant31],
  tooth41: [tooth41, cavity41, implant41],
  tooth42: [tooth42, cavity42, implant42],
  tooth43: [tooth43, cavity43, implant43],
  tooth44: [tooth44, cavity44, implant44],
  tooth45: [tooth45, cavity45, implant45],
  tooth46: [tooth46, cavity46, implant46],
  tooth47: [tooth47, cavity47, implant47],
  tooth48: [tooth48, cavity48, implant48],
};
